### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by teakhanirons** [Cimmerian-Iter/Vita-centralized-guide#1]
`Anything to share for everyone? have a cool tutorial about a modification of the vita? open an issue and share it so i can add it to the upcoming centralized guide`
should be
`Anything to share to everyone? Have a cool tutorial about a modification for the Vita? Open an issue and share it so I can add it to the upcoming centralized guide.`
Other than that every piece of content this repository has looks good.

**Comment by Cimmerian-Iter** [comment]
thanks will merge the modification

**Comment by teakhanirons** [comment]
No problem, I love having another guide.

**Comment by Cimmerian-Iter** [comment]
Wish come true

**Comment by teakhanirons** [comment]
Typo not fixed

**Comment by Cimmerian-Iter** [comment]
Waiting for my collaborator to finish proof reading the plugin part before merging all the changes
